### ISSUE TITLE
Not checking subdomain for codeberg.org [BUG]

### ISSUE THREAD

**Issue by GLSW2020** [fmhy/FMHYFilterlist#17]
When you go to Disblock Origin because it is on codeberg and codeberg.org is starred under dev tools/git tools, it is starring Disblock-Origin as well. It should show "safe to browser" rather than "starred". I checked a few other ones like github.com and addons.mozilla.org but they work fine.

To recreate the bug go to [Disblock-Origin](https://codeberg.org/AllPurposeMat/Disblock-Origin) and it'll show up as starred.

**Comment by MIOGMIOG** [comment]
As I've said in #18, this is the wrong repo to report FMHY siteguard issues, the https://github.com/kenhendricks00/FMHY-SafeGuard is the right repozitory for this

**Comment by GLSW2020** [comment]
Oh, sorry. The issue is that the extension has linked this repo's issue page to report for any mistakes.
