### ISSUE TITLE
https://github.com/yoshiask/FluentStore?tab=readme-ov-file [BUG]

### ISSUE THREAD

**Issue by githlacker** [fmhy/FMHYFilterlist#18]
i was trying the extension on FluentStore site and it worked at first but after only going backward then forward in the page it stopped working and didn't put it as a starred site (this is happening in most sites)

**Comment by MIOGMIOG** [comment]
This repo is for the list of unsafe websites, you should've created an issue in the kenhendricks00/FMHY-SafeGuard repo instead.
